#!/usr/bin/env Rscript

# This R scripts opens the binary file generated by the Langevin MD code for 
#  LJ clusters, and reads the energies it contains

# Format of the bin file :
#   at the beginning a 64 bits usigned int containing the number of records : N
#   then N times 4 double numbers : time (ps) and potential, kinetic and total energies (kj/mol)

args = commandArgs(trailingOnly=TRUE)

if (length(args)==0) {
  stop("One argument must be supplied (energy file name).n", call.=FALSE)
}

fname <- args[1]

fi <- file(fname,"rb")

# read one 64 unsigned integer corresponding to number of steps
N <- readBin(fi,'integer',size=8)

print( paste("Number of records in energy file",fname,"is :",N) )

df <- data.frame(time=double(),epot=double(),ekin=double(),etot=double())

for(i in 1:N)
{
  # read 4 double precision
  df[i,] <- readBin(fi,'numeric',size=8,n=4)
}

png('epot.png',width=1200,height=800)
par(cex=1.75,lwd=3)
plot(df$time,df$epot,xlab="Time (ps)",ylab="Potential Energy (kJ/mol)",main="",type="b")
dev.off()

png('ekin.png',width=1200,height=800)
par(cex=1.75,lwd=3)
plot(df$time,df$ekin,xlab="Time (ps)",ylab="Kinetic Energy (kJ/mol)",main="",type="b")
dev.off()

png('etot.png',width=1200,height=800)
par(cex=1.75,lwd=3)
plot(df$time,df$etot,xlab="Time (ps)",ylab="Total Energy (kJ/mol)",main="",type="b")
dev.off()
